image: node:alpine

stages:
  - install
  - build
  - deploy

cache:
  key: react_cache
  paths:
    - node_modules

job_install:
  stage: install
  tags:
    - mike
  script:
    - npm install

job_build:
  stage: build
  tags:
    - mike
  script:
    - npm run build

job_deploy_by_docker:
  image: docker:latest
  stage: deploy
  tags:
    - mike
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  script:
    - docker build -t react_demo .
    - if [ $(docker ps -aq --filter name=react_container) ]; then docker rm -f react_container; fi
    - docker run -d -p 8050:80 --name react_container react_demo
    - echo 'Deploy successful! visit http://192.168.3.15:8050'
