version: "3.8"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    ports:
      - "9980:80"
      - "9922:22"
    volumes:
      - "/Users/kosanfai/necs/gitlab-config:/etc/gitlab"
      - "/Users/kosanfai/necs/gitlab-logs:/var/log/gitlab"
      - "/Users/kosanfai/necs/gitlab-data:/var/opt/gitlab"

  # jenkins:
  #   image: jenkins/jenkins:lts
  #   container_name: jenkins
  #   restart: always
  #   ports:
  #     - "8081:8080"
  #     - "50000:50000"
  #   volumes:
  #     - "/Users/kosanfai/necs/jenkins-data:/var/jenkins_home"
  #   depends_on:
  #     - gitlab
